name: build-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: build project
        run: make project-build

      - name: test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          # Set CC_TEST_REPORTER_ID as secret of your repo
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: "${{github.workspace}}/app/src/main/java"
        with:
          # The report file must be there, otherwise Code Climate won't find it
          coverageCommand: make run-test
          coverageLocations: ${{github.workspace}}/app/build/jacoco/test/jacocoTestReport.xml:jacoco